DOMAIN = "vicente_energy"

CONF_SOLAR_POWER_ENTITY = "solar_power_entity"
CONF_SOLAR_FORECAST_ENTITIES = "solar_forecast_entities"
CONF_BATTERY_SOC_ENTITY = "battery_soc_entity"
CONF_HOUSE_LOAD_ENTITY = "house_load_entity"
CONF_HOUSE_LOAD_FORECAST_ENTITY = "house_load_forecast_entity"
CONF_HOUSE_BUDGET_ENTITY = "house_budget_entity"
CONF_LOCATION_NAME_ENTITY = "location_name_entity"
CONF_BATTERIES_CAPACITY_ENTITY = "batteries_capacity_entity"
CONF_BATTERIES_EFFICENCY_ENTITY = "batteries_efficiency_entity"
CONF_EVCHARGER_POWER_ENTITY = "charger_power_entity"
CONF_EVCHARGER_STATE_ENTITY = "charger_state_entity"
CONF_EVCHARGER_BUDGET_ENTITY = "charger_budget_entity"
CONF_EVCHARGING_MODE_ENTITY = "charging_mode_entity"

CONF_LOCATION_NAME = "location_name"
CONF_BATTERY_CAPACITY_KWH = "battery_capacity_kwh"
CONF_RESERVE_SOC_PCT = "reserve_soc_pct"
CONF_STORAGE_EFFICIENCY = "storage_efficiency"
CONF_MAX_CHARGER_POWER_KW = "max_charger_power_kw"
CONF_SESSION_LEARNING_ALPHA = "session_learning_alpha"
CONF_BUDGET_UPDATE_INTERVAL_HOURS = "budget_update_interval_hours"
CONF_UPDATE_INTERVAL_MINUTES = "update_interval_minutes"

CONF_RESERVE_SOC = CONF_RESERVE_SOC_PCT
CONF_SOLAR_WEIGHT = "solar_importance_weight"
