reset_history:
  description: Clears all learned biases and history.
  fields: {}
  name: Reset Vicente Energy History
set_power_level:
  description: Set a manual charge power level (kW).
  fields:
    power_level_kw:
      description: Desired power level in kW
      example: 2.5
  name: Set Vicente Energy Charge Power Level
